import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Adminnavbar from "@/components/Adminnavbar";
import Adminsidebar from "@/components/Adminsidebar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Adminnavbar/>
      <div className="flex">
        <Adminsidebar />
        <div className="flex-1 pl-4 bg-light-blue-500 pt-2">{children}</div>
      </div>
      </body>
    </html>
  );
}
