import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Usernavbar from "@/components/Usernavbar";
import Usersidebar from "@/components/Usersidebar";
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Usernavbar/>
        <div className="flex">
        <Usersidebar />
        <div className="flex-1  bg-gray-400 ">{children}</div>
        </div>
      </body>
    </html>
  );
}
